### ISSUE TITLE
The code from the documentation throws an error: TypeError: DbMigrate is not a constructor

### ISSUE THREAD

**Issue by gomin1d** [QuentinBellus/simple-mysql-migrate#7]
I took the code from the documentation and pasted it into my `index.js` file:

```
import DbMigrate from 'simple-mysql-migrate';

const migration = new DbMigrate ({
    "host": "localhost",
    "port": 3306,
    "username": "user",
    "password": "pass",
    "database": "database"
});

migration.setMigrationPath("migrations/");
await migration.migrate();
console.log('migrate done');
```

installed the dependency via `npm install simple-mysql-migrate`

But I get the error:
```
file:///F:/VisualStudioProjects/gomin1dproject22-app/index.js:3
const migration = new DbMigrate ({
                  ^

TypeError: DbMigrate is not a constructor
    at file:///F:/VisualStudioProjects/gomin1dproject22-app/index.js:3:19
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12)
```

**Comment by gomin1d** [comment]
If i use commonjs, then i get error:  
```
[nodemon] starting `node index.js`
F:\VisualStudioProjects\gomin1dproject22-app\node_modules\simple-mysql-migrate\dist\index.js:49
        this.filesPath = "";
                       ^

TypeError: Cannot set properties of undefined (setting 'filesPath')
    at DbMigrate (F:\VisualStudioProjects\gomin1dproject22-app\node_modules\simple-mysql-migrate\dist\index.js:49:24)
    at Object.<anonymous> (F:\VisualStudioProjects\gomin1dproject22-app\index.js:4:19)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49
```

**Comment by QuentinBellus** [comment]
It is originally made for typescript projects, but it should work fine with javascript.

I just tested it in javascript with this code, without issue:

```js
const DbMigrate = require('simple-mysql-migrate').default;

const migration = new DbMigrate({
    host: "127.0.0.1",
    port: 3306,
    username: "test",
    password: "test",
    database: "test"
});

migration.setMigrationPath("./mysql");
migration.migrate();
```

Let me know if that helps.

**Comment by gomin1d** [comment]
> It is originally made for typescript projects, but it should work fine with javascript.
> 
> I just tested it in javascript with this code, without issue:
> 
> ```js
> const DbMigrate = require('simple-mysql-migrate').default;
> 
> const migration = new DbMigrate({
>     host: "127.0.0.1",
>     port: 3306,
>     username: "test",
>     password: "test",
>     database: "test"
> });
> 
> migration.setMigrationPath("./mysql");
> migration.migrate();
> ```
> 
> Let me know if that helps.

This code works. `.default` seems to make everything work. I'm still new to JavaScript. Please tell me `.default` is somehow related to TypeScript?

**Comment by QuentinBellus** [comment]
We don't have to do that in typescript, but it seems like it's necessary to point to which export we want to use in this case.

Glad it's working for you now!
